ignore_theme_config: true
title: "Go for Education Chaklala"
email: "info@gfe-chaklala.org"
description: ""
url: "https://gfe-chaklala.org"
author:
  name: Go for Education ChakLala e.V.
  email: "info@gfe-chaklala.org"

theme: minima

minima:
  skin: auto
  
plugins:
  - jekyll-feed
  - jekyll-maps
  
maps:
  google:
    api_key: AIzaSyBRAWiUMQD-6V8IZiuBGJHN6qmpmnrgO6U
    
includes:
  - _pages