title: "Go for Education Chaklala"
email: "info@gfe-chaklala.org"
description: ""
url: "https://gfe-chaklala.org"
author:
  name: Go for Education ChakLala e.V.
  email: "info@gfe-chaklala.org"

theme: minima

minima:
  skin: auto
  nav_pages:
    - aktuelles.markdown
    - kontakt.markdown

  social_links:
    - title: GfE ChakLala on Facebook
      icon: facebook
      url: "https://facebook.com/GfEChakLala"
    - title: Datenschutz
      icon: shield
      fa_namespace: regular
      url: "/datenschutz.html"
excerpt_separator: <!--more-->

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-maps

collections:
  carousels:
    output: false

maps:
  google:
    api_key: AIzaSyBRAWiUMQD-6V8IZiuBGJHN6qmpmnrgO6U
